### PR TITLE
Add the ability to export skeletons as XML

### PR DESCRIPTION
**Pull request by youdontown**
This is a useful feature for debugging. This format is not actually used by any editors, but it is human readable and can help the user understand the format the skeleton is in.

### CODE REVIEW

**Comment by Demonslayerx8** [comment]
Would this also be capable of bone edits?

**Comment by youdontown** [comment]
> Would this also be capable of bone edits?

I could also write an importer, if it would be useful.

**Comment by Demonslayerx8** [comment]
> > Would this also be capable of bone edits?
> 
> I could also write an importer, if it would be useful.

Yeah would be useful, would help on editing bonesets w/o the bone structure getting all messed up, I'd be able to use the physic bones from Bayo's head and use em as a cape or scarf effect when I move them to the bust, if it's able to edit bone positions from Head to Bust

**Comment by youdontown** [comment]
> Yeah would be useful, would help on editing bonesets w/o the bone structure getting all messed up, I'd be able to use the physic bones from Bayo's head and use em as a cape or scarf effect when I move them to the bust, if it's able to edit bone positions from Head to Bust

I'm kinda a newbie to 3D transformations. AFAIK this would only affect the T-pose. Is that still appealing?

The way the animation gets applied to the T-pose, I'm not entirely sure if the bone edits would stick. But I can find out.

**Comment by Demonslayerx8** [comment]
Oh I won't be using it for animations, I'll be using it for mod making for ultimate itself. Moving the bone children's in 3ds max and importing the changes to StudioSB throws off the bone order for every single bone, plus it edits most bone value's thus when saved, the nusktb is unable to be compressed.

**Comment by youdontown** [comment]
> Oh I won't be using it for animations, I'll be using it for mod making for ultimate itself. Moving the bone children's in 3ds max and importing the changes to StudioSB throws off the bone order for every single bone, plus it edits most bone value's thus when saved, the nusktb is unable to be compressed.

Then yes this would probably help.

**Comment by Demonslayerx8** [comment]
Nice nice, I'd be willing to test that.

**Comment by youdontown** [comment]
Ok I have something that works.

**Comment by youdontown** [comment]
You can give this a try - use my repo as this hasn't merged yet. Load up a model, export the XML, edit its attributes, and then import it back in again.

The limitation is that you can't add, subtract, or rename bones. If that's something you need, that's going to be a bit harder (I haven't figured out the mesh and how it maps to the bones yet).

**Pull request merged**
